const $=id=>document.getElementById(id);let state,miniToken='';const base='/helpdesk-clients/api/';
const templates={
 aipbx:{url:'https://aipbx.ru/api',operations:[{id:'cabinet',description:'Ассистенты и баланс кабинета',scope:'cabinet'},{id:'analytics',description:'Настройки и результаты конкретного проекта речевой аналитики',scope:'analytics'}]},
 http:{url:'https://example.com/api',operations:[{id:'client',description:'Данные клиента',method:'GET',path:'/clients/{account_id}'},{id:'search',description:'Поиск в RAG по вопросу',method:'POST',path:'/search',params:{tenant:'{account_id}'},query_param:'query'}]},
 postgres:{host:'db.example.com',port:5432,database:'support',sslmode:'require',operations:[{id:'client',description:'Данные выбранного клиента',query:'SELECT id,name FROM customers WHERE id=%(account_id)s LIMIT 20'}]},
 mysql:{host:'db.example.com',port:3306,database:'support',tls:true,operations:[{id:'client',description:'Данные выбранного клиента',query:'SELECT id,name FROM customers WHERE id=%(account_id)s LIMIT 20'}]},
 ssh:{host:'server.example.com',port:22,host_fingerprint:'SHA256:REPLACE',operations:[{id:'logs',description:'Последние записи журнала клиента',argv:['tail','-n','80','--','{log_path}']}]},
 knowledge:{operations:[{id:'search',description:'Поиск в документации клиента'}],documents:[{title:'Продукт и поддержка',text:'Введите подтверждённые сведения и инструкции.'}]},
 mcp:{url:'https://example.com/mcp',operations:[{id:'search',description:'Разрешённый поиск по базе знаний клиента',tool:'search_knowledge',arguments:{tenant_id:'{account_id}'},query_argument:'query'}]}
};
const help={aipbx:'Параметры привязки: account_email (email кабинета), cabinet_id (проверка владельца), project_id (если нужна аналитика). Токен задаётся ниже.',http:'Настройте только операции чтения. Параметры клиента подставляются сервером, модель не выбирает URL.',postgres:'Используйте отдельную учётную запись только для чтения. Запросы параметризуются значениями привязки.',mysql:'MySQL/MariaDB: отдельный пользователь только для чтения. TLS включён по умолчанию.',ssh:'Укажите проверенный fingerprint сервера и argv команд чтения. Ключ вводится ниже; модель не генерирует команды.',knowledge:'Документы хранятся с источником. В ответ передаются только найденные фрагменты.',mcp:'Поддерживается Streamable HTTP MCP 2025-03-26/06-18/11-25. Указывайте только проверенные инструменты чтения; stdio не запускается.'};
function notice(text){$('notice').textContent=text;$('notice').hidden=false;setTimeout(()=>{$('notice').hidden=true},6500)}
async function api(path,data){const r=await fetch(base+path,{method:data===undefined?'GET':'POST',headers:{...(data===undefined?{}:{'Content-Type':'application/json'}),...(miniToken?{'Authorization':'Bearer '+miniToken}:{})},body:data===undefined?undefined:JSON.stringify(data)});const v=await r.json();if(!r.ok){if(r.status===401){$('app').hidden=true;$('login').hidden=false}throw Error(v.error||'Ошибка запроса')}return v}
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
function options(select,items,label,empty){const previous=select.value;select.replaceChildren();if(empty!==undefined){const o=el('option',empty);o.value='';select.append(o)}for(const item of items){const o=el('option',label(item));o.value=item.id;select.append(o)}if([...select.options].some(o=>o.value===previous))select.value=previous}
function setForm(form,value){form.reset();for(const [k,v] of Object.entries(value)){const f=form.elements.namedItem(k);if(!f)continue;if(f.type==='checkbox')f.checked=!!v;else f.value=v??''}}
function cards(id,items,title,body){$(id).replaceChildren();if(!items.length){$(id).append(el('p','Пока нет записей. Добавьте первую карточку.'));return}for(const item of items){const n=el('article',undefined,'card');n.append(el('span','#'+item.id,'badge'),el('h3',title(item)),el('p',body(item)));$(id).append(n)}}
async function load(){state=await api('state');$('login').hidden=true;$('app').hidden=false;$('who').textContent=state.me.name;document.querySelectorAll('.admin').forEach(n=>n.hidden=state.me.role!=='admin');render()}
function render(){
 cards('clientList',state.clients,x=>x.name,x=>[x.active?'Активен':'Выключен',...x.emails,'Источников: '+x.bindings.filter(b=>b.active).length,x.notes].filter(Boolean).join('\n'));
 cards('sourceList',state.sources,x=>x.name,x=>[x.kind,x.active?'Включён':'Выключен',x.hasSecret?'Доступы сохранены':'Без сохранённых доступов','Операций: '+x.config.operations.length].join('\n'));
 cards('userList',state.users,x=>x.name,x=>[x.login,x.role==='admin'?'Владелец':'Исполнитель',x.active?'Вход разрешён':'Вход закрыт'].join('\n'));
 options($('clientEdit'),state.clients,x=>'#'+x.id+' '+x.name,'Новый клиент');options($('clientExecutor'),state.users.filter(x=>x.active),x=>x.name,'Не назначен');options($('sourceEdit'),state.sources,x=>'#'+x.id+' '+x.name,'Новый источник');options($('userEdit'),state.users.filter(x=>x.role!=='admin'),x=>x.name,'Новый исполнитель');
 for(const id of ['bindingClient','checkClient'])options($(id),state.clients.filter(x=>x.active),x=>'#'+x.id+' '+x.name,'Выберите клиента');
 options($('bindingSource'),state.sources,x=>'#'+x.id+' '+x.name,'Выберите источник');clientEdit();sourceEdit();userEdit();bindingEdit();checkOptions();if(window.renderTickets)renderTickets();
}
function clientEdit(){const x=state.clients.find(x=>String(x.id)===$('clientEdit').value);setForm($('clientForm'),x?{...x,emails:x.emails.join('\n')}:{id:'',active:true})}
function sourceEdit(){const x=state.sources.find(x=>String(x.id)===$('sourceEdit').value);setForm($('sourceForm'),x?{...x,config:JSON.stringify(x.config,null,2)}:{id:'',kind:'aipbx',active:false,config:JSON.stringify(templates.aipbx,null,2)});$('secretStatus').textContent=x?.hasSecret?'Доступы уже сохранены. Пустые поля оставят их без изменения.':'Доступы ещё не заданы.';kindHelp()}
function userEdit(){const x=state.users.find(x=>String(x.id)===$('userEdit').value);setForm($('userForm'),x||{id:'',active:true})}
function kindHelp(){$('kindHelp').textContent=help[$('kind').value]}
function bindingEdit(){const cl=state.clients.find(x=>String(x.id)===$('bindingClient').value);const source=state.sources.find(x=>String(x.id)===$('bindingSource').value);const b=cl?.bindings.find(x=>x.source_id===source?.id);const f=$('bindingForm');f.elements.params.value=JSON.stringify(b?.params||{},null,2);f.elements.instructions.value=b?.instructions||'';f.elements.active.checked=b?.active??true;$('operationChoices').replaceChildren(el('label','Разрешённые операции'));for(const op of source?.config.operations||[]){const label=el('label',undefined,'check');const input=el('input');input.type='checkbox';input.name='operation';input.value=op.id;input.checked=b?.operations.includes(op.id)||false;label.append(input,el('span',op.id+' · '+op.description));$('operationChoices').append(label)}}
function checkOptions(){const cl=state.clients.find(x=>String(x.id)===$('checkClient').value);const items=[];for(const b of cl?.bindings||[]){const source=state.sources.find(x=>x.id===b.source_id);if(!source||(state.me.role!=='admin'&&(!b.active||!source.active)))continue;for(const op of source.config.operations)if(b.operations.includes(op.id))items.push({id:source.id+':'+op.id,label:source.name+' · '+op.description+(!b.active||!source.active?' · выключен, проверка':'')})}options($('checkOperation'),items,x=>x.label,'Выберите операцию')}
function json(value){try{return JSON.parse(value)}catch{throw Error('Проверьте синтаксис JSON')}}
function submit(id,path,collect,after){$(id).addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;const button=form.querySelector('button:not([type="button"])');button.disabled=true;try{const result=await api(path,collect(form));notice('Сохранено');await load();if(after)after(result)}catch(err){notice(err.message)}finally{button.disabled=false}})}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;try{const auth=await api('login',{login:f.elements.login.value,password:f.elements.password.value,initData:telegramInitData()});miniToken=auth.token||'';f.elements.password.value='';await load()}catch(err){notice(err.message)}});
$('logout').onclick=async()=>{try{await api('logout',{});miniToken='';$('app').hidden=true;$('login').hidden=false}catch(e){notice(e.message)}};
$('tabs').onclick=e=>{const tab=e.target.dataset.tab;if(!tab)return;document.querySelectorAll('.panel').forEach(n=>n.hidden=n.id!==tab);document.querySelectorAll('#tabs button').forEach(n=>n.classList.toggle('selected',n.dataset.tab===tab));if(tab==='tickets'&&window.loadTickets)loadTickets()};
$('clientEdit').onchange=clientEdit;$('sourceEdit').onchange=sourceEdit;$('userEdit').onchange=userEdit;$('kind').onchange=kindHelp;$('example').onclick=()=>{$('sourceConfig').value=JSON.stringify(templates[$('kind').value],null,2)};$('bindingClient').onchange=bindingEdit;$('bindingSource').onchange=bindingEdit;$('checkClient').onchange=checkOptions;
submit('clientForm','client',f=>({id:Number(f.elements.id.value)||null,name:f.elements.name.value,notes:f.elements.notes.value,emails:f.elements.emails.value.split(/[\s,;]+/).filter(Boolean),executor_id:Number(f.elements.executor_id.value)||null,active:f.elements.active.checked}));
submit('sourceForm','source',f=>{const credentials={};for(const key of ['username','password','bearer','private_key','passphrase'])if(f.elements[key].value)credentials[key]=f.elements[key].value;if(f.elements.headers.value)credentials.headers=json(f.elements.headers.value);return {id:Number(f.elements.id.value)||null,name:f.elements.name.value,kind:f.elements.kind.value,config:json(f.elements.config.value),active:f.elements.active.checked,clearSecret:f.elements.clearSecret.checked,credentials}});
submit('bindingForm','binding',f=>({client_id:Number(f.elements.client_id.value),source_id:Number(f.elements.source_id.value),params:json(f.elements.params.value),instructions:f.elements.instructions.value,operations:[...f.querySelectorAll('input[name="operation"]:checked')].map(n=>n.value),active:f.elements.active.checked}));
submit('userForm','user',f=>({id:Number(f.elements.id.value)||null,name:f.elements.name.value,login:f.elements.login.value,password:f.elements.password.value,telegram_id:f.elements.telegram_id.value,active:f.elements.active.checked}));
$('checkForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;const [sid,op]=$('checkOperation').value.split(':');const button=f.querySelector('button');button.disabled=true;try{const result=await api('check',{client_id:Number(f.elements.client_id.value),source_id:Number(sid),operation:op,query:f.elements.query.value,ticket_id:Number(f.elements.ticket_id.value)||null});$('checkResult').textContent=JSON.stringify(result,null,2);$('checkResult').hidden=false}catch(err){notice(err.message)}finally{button.disabled=false}};
function telegramInitData(){return window.Telegram?.WebApp?.initData||new URLSearchParams(location.hash.slice(1)).get('tgWebAppData')||''}
function telegramReady(){window.Telegram?.WebApp?.ready();window.Telegram?.WebApp?.expand()}
telegramReady();document.querySelector('script[src^="https://telegram.org/js/telegram-web-app.js"]')?.addEventListener('load',telegramReady);load().catch(()=>{});
let ticketOffset=0,currentTicket;
const labels={open:'Новый',in_progress:'В работе',waiting_client:'Ожидает клиента',resolved:'Решён',closed:'Закрыт',received:'Подготовка ответа',needs_mapping:'Нужна настройка клиента',pending_approval:'Ожидает согласования',sending:'Отправляется',sent:'Ответ отправлен',rejected:'Черновик отклонён',send_uncertain:'Неопределённый результат SMTP',ignored:'Автоматическое письмо'};
const events={email_received:'Получено письмо',thread_reopened:'Новый ответ в переписке',registry_setup_required:'Нужна настройка клиента',preparation_started:'Начата обработка',model_read_plan_started:'Модель выбирает чтения',model_read_plan:'Модель выбрала чтения',source_read_started:'Запрос источника',source_read_finished:'Результат чтения',operator_source_read:'Проверка источника сотрудником',model_draft_started:'Подготовка черновика',model_draft_proposed:'Предложен ответ',preparation_failed:'Ошибка подготовки',operator_comment:'Комментарий сотрудника',case_status_changed:'Статус обращения изменён',executor_assigned:'Назначен исполнитель',preparation_retried:'Повтор подготовки',operator_draft_edited:'Черновик изменён сотрудником',draft_revision:'Сохранена версия черновика',approved_sending:'Одобрено, начата отправка',smtp_accepted:'SMTP принял ответ',send_uncertain:'Требуется проверка доставки',rejected:'Черновик отклонён',registry_client_bound:'Клиент привязан',registry_configuration_ready:'Настройки клиента готовы',preparation_superseded:'Подготовка отменена из-за изменений обращения',mapping_required:'Требуется привязка клиента/источника',project_selected:'Проект выбран',agreement_approved:'Договорённость согласована'};
function date(v){return new Date(v).toLocaleString('ru-RU')}
async function loadTickets(){try{const result=await api('tickets?offset='+ticketOffset+'&case='+encodeURIComponent($('ticketFilter').value)+'&search='+encodeURIComponent($('ticketSearch').value));$('ticketCount').textContent=' Всего: '+result.total;$('ticketPrev').disabled=ticketOffset===0;$('ticketNext').disabled=ticketOffset+50>=result.total;$('ticketList').replaceChildren();for(const t of result.tickets){const card=el('article',undefined,'card');card.append(el('span','#'+t.id+' · '+labels[t.case_status],'badge'),el('h3',t.subject||'Без темы'),el('p',[(t.client_name||'Клиент не привязан'),t.sender,labels[t.status],t.executor_name?'Исполнитель: '+t.executor_name:'Исполнитель не назначен',date(t.updated_at),t.last_error?'Ошибка: '+t.last_error:''].filter(Boolean).join('\n')));const b=el('button','Открыть','quiet');b.onclick=()=>openTicket(t.id);card.append(b);$('ticketList').append(card)}if(!result.tickets.length)$('ticketList').append(el('p','Обращений по выбранному фильтру нет.'))}catch(e){notice(e.message)}}
window.loadTickets=loadTickets;window.renderTickets=()=>{if(!$('tickets').hidden)loadTickets()};
async function ticketAction(action,extra={}){try{const result=await api('ticket-action',{ticket_id:currentTicket.id,action,...extra});notice(result.message||'Сохранено');await openTicket(currentTicket.id);await loadTickets()}catch(e){notice(e.message)}}
async function openTicket(id){try{const t=await api('ticket?id='+id);currentTicket=t;const box=$('ticketDetail');box.replaceChildren();box.hidden=false;box.append(el('span','#'+t.id+' · '+labels[t.case_status]+' · '+labels[t.status],'badge'),el('h2',t.subject||'Без темы'),el('p','От: '+t.sender+' · Клиент: '+(t.registry_client_id||'не привязан')));
 const controls=el('div',undefined,'grid');const status=el('select');for(const [key,label] of Object.entries(labels).filter(([key])=>['open','in_progress','waiting_client','resolved','closed'].includes(key))){const o=el('option',label);o.value=key;status.append(o)}status.value=t.case_status;status.onchange=()=>ticketAction('case',{case_status:status.value});const l=el('label','Статус обращения');l.append(status);controls.append(l);
 if(state.me.role==='admin'){const select=el('select');options(select,state.users.filter(u=>u.active),u=>u.name,'По карточке клиента');select.value=t.executor_id||'';select.onchange=()=>ticketAction('assign',{executor_id:Number(select.value)||null});const l=el('label','Исполнитель');l.append(select);controls.append(l)}box.append(controls);
 if(state.me.role==='admin'&&['needs_mapping','received','sent','rejected','ignored'].includes(t.status)){const select=el('select');options(select,state.clients.filter(c=>c.active),c=>'#'+c.id+' '+c.name,'Выберите клиента');select.value=t.registry_client_id||'';const label=el('label','Привязать обращение к клиенту');label.append(select);const link=el('button','Привязать клиента','quiet');link.onclick=()=>ticketAction('client',{client_id:Number(select.value)});box.append(label,link)}
 if(['received','needs_mapping','rejected','pending_approval'].includes(t.status)){const retry=el('button','Повторить подготовку','quiet');retry.onclick=()=>ticketAction('retry');box.append(retry)}
 const comment=el('textarea');comment.rows=3;comment.placeholder='Внутренний комментарий';const add=el('button','Добавить комментарий','quiet');add.onclick=()=>ticketAction('comment',{text:comment.value});box.append(el('h3','Работа с обращением'),comment,add);
 if(t.draft){box.append(el('h3','Текущий черновик · версия '+t.revision));const draft=el('textarea');draft.rows=10;draft.value=t.draft;draft.disabled=t.status!=='pending_approval';box.append(draft);if(t.status==='pending_approval'){const edit=el('button','Сохранить новую версию','quiet');edit.onclick=()=>ticketAction('edit',{revision:t.revision,text:draft.value});box.append(edit);if(state.me.role==='admin'&&!['closed','resolved'].includes(t.case_status)){const approve=el('button','Одобрить и отправить');draft.addEventListener('input',()=>{approve.disabled=draft.value!==t.draft});approve.onclick=()=>{if(confirm('Отправить сохранённую версию '+t.revision+' адресату '+t.sender+'? Несохранённые изменения не отправятся.'))ticketAction('approve',{hash:t.draft_hash})};const reject=el('button','Отклонить','quiet');reject.onclick=()=>ticketAction('reject',{hash:t.draft_hash});box.append(approve,reject)}}}
 box.append(el('h3','Переписка'));for(const m of t.messages){const d=el('details');d.append(el('summary',(m.direction==='inbound'?'Входящее':'Ответ')+' · '+date(m.created_at)+' · '+m.subject),el('pre',m.body));box.append(d)}
 box.append(el('h3','Журнал действий'));for(const event of t.timeline){const d=el('details');d.append(el('summary',date(event.created_at)+' · '+(events[event.event]||event.event)+' · '+(event.actor==='executor:model'?'Модель · DeepSeek':event.actor?.startsWith('user:')?(state.users.find(u=>String(u.id)===event.actor.slice(5))?.name||'Сотрудник'):event.actor==='mail'?'Почта':event.actor||'система')),el('pre',JSON.stringify(event.data,null,2)));box.append(d)}
 box.append(el('h3','Версии ответов'));for(const r of t.revisions){const d=el('details');d.append(el('summary','Версия '+r.revision),el('pre',r.body));box.append(d)}
 if(t.previous.length){box.append(el('h3','Другие обращения клиента'));for(const previous of t.previous){const b=el('button','#'+previous.id+' · '+previous.subject,'quiet');b.onclick=()=>openTicket(previous.id);box.append(b)}}box.scrollIntoView({behavior:'smooth',block:'start'});
 }catch(e){notice(e.message)}}
$('ticketRefresh').onclick=()=>{ticketOffset=0;loadTickets()};$('ticketFilter').onchange=()=>{ticketOffset=0;loadTickets()};$('ticketPrev').onclick=()=>{ticketOffset=Math.max(0,ticketOffset-50);loadTickets()};$('ticketNext').onclick=()=>{ticketOffset+=50;loadTickets()};
setInterval(()=>{if(state&&!$('tickets').hidden)loadTickets()},30000);
