name: PBX Docker

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    step:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/krasterisk/simplePBX/pbx
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "production"
